FROM sbtscala/scala-sbt:eclipse-temurin-jammy-8u352-b08_1.8.2_3.2.2
ENV JAVA_OPTS=-Xmx1G
# Default powerline10k theme, no plugins installed
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)"