FROM hseeberger/scala-sbt:17.0.2_1.6.2_3.1.1
ENV JAVA_OPTS=-Xmx1G
# Default powerline10k theme, no plugins installed
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)"